language: python
python:
  - "3.4"

# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
script: py.test && pylint ChildSoldier

# notifications
notifications:
  slack: outreach2015:rAnIvuM3klyHrwQDQJHvXbJ1